### PR TITLE
Fix install warnings

### LINKED ISSUE #146: Warnings when installing hapi-pulse
Hi I am getting the following yarn warnings: 

warning hapi-pulse > @hapi/joi@17.0.2: Switch to 'npm install joi'
warning hapi-pulse > @hapi/joi > @hapi/address@4.1.0: Moved to 'npm install @sideway/address'
warning hapi-pulse > @hapi/joi > @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'
warning hapi-pulse > @hapi/joi > @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'

I installed hapi-pulse 3.0.0
I am using @hapi/hapi: 20.1.3 and joi: 17.4.0

### PR DESCRIPTION
**Pull request by alferpal**
Updates joi to fix install warnings

Fixes #146

### CODE REVIEW

**Comment by marcuspoehls** [comment]
@alferpal Thank you Alex!

**Comment by jmldavis** [comment]
@marcuspoehls I don't think NPM is up to date with these changes

**Comment by marcuspoehls** [comment]
@jmldavis thank you for the reminder. I’ve published version `3.0.1` to NPM 🙂

**Comment by jmldavis** [comment]
@marcuspoehls thanks so much. (I like the look of Supercharge, by the way).

**Comment by marcuspoehls** [comment]
@jmldavis That’s awesome 😍 thank you!

**Pull request merged**
